# Generated by Django 4.1.5 on 2023-05-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0002_aboutpage_contactpage_gallery_homepage_servicespage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
